// Importing the User Model to use it to create a new user in the post signup request.
// Importing the "bcryptjs" package to implement the hash password in the user creation for security.

const User = require('../models/user');
const bcrypt = require('bcryptjs');

const crypto = require('crypto'); // Crypto is the in-built nodejs provided package to create a secure tokens to be used in the application.

const nodemailer = require('nodemailer');
const nodemailertransporter = require('nodemailer-sendgrid-transport');

const mailTransport = nodemailer.createTransport(nodemailertransporter({
    auth: {
        api_user: ''
    }
}));

// getSignUpPage() is the middleware function to handle the GET request to respond when user tries to singup to the applicaton.
// navigation -> clicked on "Signup" in the menu to redirect to view "signup" page.
exports.getSignUpPage = (req, res, next) => {
    let message = req.flash('error');
        if(message.length > 0){
            message = message[0];
        }
        else{
            message = null;
        }
    res.render('auth/signup', {
        path: '/signup',
        pageTitle: 'SignUp',
        isAuthenticated: false,
        errorMessage: message,
    });
}

// postSignUpPage() is the middleware function to handle the POST request to respond when user clicked on "singup" button in the Signup page.
// navigation -> clicked on "Signup" button.
exports.postSignUpPage = (req, res, next) => {
    // Collecting the user details like email and password.
    const email = req.body.email;
    const password = req.body.password;
    // Checking if the user already exists in the database. if yes -> redirect to singup page.
    User.findOne({email: email}).then(user => {
        if(user){
            req.flash('error', 'E-mail already exists, Please try with a new email');
            return res.redirect('/signup');
        }
    // If not an existing user -> before creating a new user the password is hashed for security and then creating a new user with the User model.
        return bcrypt.hash(password, 12).then(hasedPassword => {
            const user = new User({
                email: email,
                password: hasedPassword,
                cart: {items: []}
            });
            return user.save();
            }).then(result => {
                res.redirect('/login');
                return mailTransport.sendMail({
                    to: email,
                    from: 'snadi043@uottawa.ca',
                    html: '<h1>You are signup succedded!</h1>',
                    subject: 'You are successfully signed up',
                    text: 'Success'
                });
            }).catch(err => {console.log(err)});
    });
}

// getResetPage() is the middleware function to handle the GET request to respond when user tries to reset their password from the login page of the applicaton.
// navigation -> clicked on "Login" in the menu -> Click on the "Reset Password" link -> redirect to view "reset" page.
exports.getResetPage = (req, res, next) => {
    // Enabling the error message pop-up to show on the screen using the "flash-connect" npm package installed in the applicaiton.
    let message = req.flash('error');
    if(message.length > 0){
        message = message[0];
    }
    else{
        message = null;
    }
    res.render('auth/reset', {
        pageTitle: 'Reset Password',
        path: '/reset',
        isAuthenticated: false,
        errorMessage: message,
    });
}

// postResetPage() is the middleware function to handle the POST request to respond when user clicked on "Reset Password" button in the Login page.
// navigation -> clicked on "Login" in the menu -> Click on the "Reset Password" link -> redirect to view "reset" page -> Click on "Reset Password" button -> redirect to view "reset/{token}".
exports.postResetPage = (req, res, next) => {
    // Configuring the "crypto" pacakge to generate the secure token.
    crypto.randomBytes(32, (err, buffer) => {
        if(err){
            console.log(err);
            return res.redirect('/reset');
        };
        const token = buffer.toString('hex');
        // Once the token is generated, storing that token into the individual user to match the authentication of the user by checking with their email from the database.
        User.findOne({email: req.body.email})
        .then(user => {
        // If the user is not an existing user and tries to reset the password -> send an error message generated by the "connect-flash" package.
        if(!user){
            req.flash('error', 'The email entered is not registered');
            return res.redirect('/reset');
        }
        // If user exists, storing the newly generated token and the expiry data of that token into the user document in the database through the model and save the updated information.
        user.resetToken = token;
        user.resetTokenExpiry = Date.now() + 3600000;
        return user.save();
        })
        // Once the updated information is saved, then sending the email by configuring the sendgrid mail service system and fill the required information.
        .then(result => {
            res.redirect('/');
            return mailTransport.sendMail({
                from: 'snadi043@uottawa.ca',
                to: req.body.email,
                html: `
                <p>You have requested for a password reset.</p>
                <p>Please click on this <a href="http://localhost:3000/reset/${token}">link</a> to reset your password.</p>
                `,
                subject: 'Password Reset Verification',
            });
        })
        .catch(err => {
            console.log(err);
        });
    });
}

exports.getNewPassword = (req, res, next) => {
    let message = req.flash('error');
    if(message.length > 0){
        message = message[0];
    }
    else{
        message = null;
    }
    res.render('/auth/new-password', {
        path: '/new-passsword',
        pageTitle: 'New Password',
        errorMessage: message,

    });
}

exports.postNewPassword = (req, res, next) => {
    const newPassword = req.body.password;
    const token =  req.params.token;
    const userId = req.body.user._id;
    let updatedUser;
    User.findOne({user_id: userId, token: token, resetTokenExpiry: $gt }).then(
        user => {
            updatedUser = user,
            updatedUser.password = bcrypt.hash(12).then(hashedPassword => {
                newPassword = hashedPassword;
                resetToken = undefined;
                resetTokenExpiry = undefined;
            return updatedUser.save();
            }).then(result => {
                res.redirect('/login');
            });
        }
    ).catch(err => {
        console.log(err);
    });
}
